---
title: "AscRtain text"
output: md_document
---

This page demonstrates some of the functional utility of the `AscRtain` [R Package](github.com/explodecomputer/AscRtain). The `parameter_space()` function simulates values over the possible parameter space for selection into a study which could give rise to an observed OR between exposure and outcome. This plots the possible selection effects on exposure ($\beta_A$) and outcome ($\beta_Y$) which could give rise to a user-defined observed odds ratio (OR) under a true known OR of 1.


Population parameters are defined as follows: 

$P(S =1)$ denotes the proportion of the population that is in the sample. 

$P(A =1)$ denotes the proportion of the population for whom the exposure A is true. 

$P(Y =1)$ denotes the proportion of the population for whom the outcome Y is true. 

$P(\A \cap \Y)$ denotes the proportion of the population for whom A and Y are both true.\
\


Selection effects are defined as follows: 

$\beta_0$ is the baseline probability of being selected into the sample. 

$\beta_A$ is the effect on selection into the sample given A=1 is true. 

$\beta_Y$ is the effect on selection into the sample given Y=1 is true. 

$\beta_{AY}$ is the effect on selection into the sample given A=1 and Y=1 are both true.

---

